# packages in environment at C:\Users\raine\AppData\Local\Continuum\anaconda3\envs\practice_concepts:
#
# Name                    Version                   Build  Channel
certifi                   2019.6.16                py36_0  
django                    2.1                      pypi_0    pypi
django-cors-headers       2.4.0                    pypi_0    pypi
django-filter             2.1.0                    pypi_0    pypi
djangorestframework       3.9.1                    pypi_0    pypi
dry-rest-permissions      0.1.10                   pypi_0    pypi
pip                       19.1.1                   py36_0  
psycopg2                  2.8.3                    pypi_0    pypi
python                    3.6.8                h9f7ef89_7  
pytz                      2019.1                   pypi_0    pypi
setuptools                41.0.1                   py36_0  
sqlite                    3.29.0               he774522_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
wheel                     0.33.4                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
