# Generated by Django 2.1 on 2019-05-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0005_auto_20190511_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='practices',
            field=models.ManyToManyField(related_name='practices', to='practices.Practice'),
        ),
    ]
