# Generated by Django 2.1 on 2019-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_auto_20190513_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='practices',
            field=models.ManyToManyField(related_name='providers', to='practices.Practice'),
        ),
    ]
