# Generated by Django 2.1 on 2019-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0007_auto_20190513_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty',
        ),
        migrations.AddField(
            model_name='provider',
            name='specialties',
            field=models.ManyToManyField(related_name='providers', to='practices.Specialty'),
        ),
    ]
