# Generated by Django 2.1 on 2019-05-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0009_dailysummary_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('date', 'provider', 'specialty')},
        ),
    ]
