# Generated by Django 2.1 on 2019-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0012_auto_20190519_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
