# Generated by Django 2.1 on 2019-05-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0013_auto_20190519_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
