# Generated by Django 2.1 on 2019-06-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0016_auto_20190523_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysummary',
            options={'ordering': ['date']},
        ),
    ]
