# Generated by Django 2.1 on 2019-08-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0019_auto_20190805_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='practices.Entity')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='practices.Practice')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('date', 'practice')},
        ),
    ]
