# Generated by Django 2.1 on 2019-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0020_auto_20190813_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
    ]
