# Generated by Django 2.1 on 2019-08-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0022_auto_20190813_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set(),
        ),
    ]
