# Generated by Django 2.1 on 2019-05-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='entity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='practices.Entity'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='alias_1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='alias_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='credentials',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('date', 'provider')},
        ),
    ]
