# Generated by Django 2.1 on 2019-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_auto_20190503_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='specialty',
            field=models.CharField(default=20, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='visits_goal',
            field=models.IntegerField(default=20),
        ),
    ]
