# Generated by Django 2.1 on 2019-05-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0008_auto_20190513_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='practices.Specialty'),
        ),
    ]
