# Generated by Django 2.1 on 2019-05-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0011_auto_20190517_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='submitted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
