# Generated by Django 2.1 on 2019-05-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0015_auto_20190520_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='practices.Entity'),
        ),
    ]
