# Generated by Django 2.1 on 2019-08-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0018_auto_20190614_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='practices.Entity'),
        ),
    ]
