# Generated by Django 2.1 on 2019-08-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0023_auto_20190813_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='workdays',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
    ]
